export const LOAD_POKEMONS_LIST = "LOAD_POKEMONS_LIST";
export const LOAD_POKEMONS_LIST_SUCCESS = "LOAD_POKEMONS_LIST_SUCCESS";

export const LOAD_ONE_POKEMON = "LOAD_ONE_POKEMON";
export const LOAD_ONE_POKEMON_SUCCESS = "LOAD_ONE_POKEMON_SUCCESS";
